import { defineReagent } from "../reagent-types";

export const potassiumTertButoxide = defineReagent({
  kind: "reagent",
  id: "potassium-tert-butoxide",
  slug: "potassium-tert-butoxide",
  name: "Potassium tert-butoxide",
  aliases: ["KOtBu", "t-BuOK", "potassium tert-butanolate"],
  formula: "KOtBu",
  category: "Base",
  summary: "A strong, sterically hindered base used to favour E2 elimination over substitution.",
  purpose: "Removes a beta proton from alkyl halides to form alkenes through a concerted E2 pathway.",
  selectivity: "Its steric bulk often favours Hofmann elimination when multiple beta positions are available.",
  conditions: ["Anhydrous polar aprotic solvent", "Elevated temperature often favours elimination"],
  limitations: ["Poor nucleophile for substitution", "Moisture sensitive", "Can give regioisomer mixtures"],
  safety: "Strongly basic and moisture sensitive; reacts with water and protic solvents.",
  alternativeNames: ["Potassium tert-butanolate", "KOtBu", "t-BuOK"],
  reactionIds: ["e2"],
  mechanismIds: ["e2"],
  moleculeIds: ["2-bromopropane"],
  lessonIds: ["chemical-bonding", "hybridization"],
  keywords: ["bulky base", "E2", "elimination", "Hofmann product", "alkyl halide", "strong base"],
  capabilities: {
    reference: true,
    workspace: true,
    reactionExplorer: true,
    prediction: true,
    retrosynthesis: true,
  },
});
