"use client";

import Link from "next/link";
import type { ReactNode } from "react";
import { calculateMolarMass } from "@/lib/calculators";
import { getWorkspaceMolecule } from "@/content/workspace";
import { requireRelationshipPresentation } from "@/content/relationships";
import type { WorkspaceKnowledgeLink } from "@/content/workspace/workspace-types";
import { useWorkspace } from "../WorkspaceProvider";

function ToolLink({ href, children }: { href: string; children: ReactNode }) {
  return <Link href={href} className="inline-flex rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white hover:bg-slate-800">{children}</Link>;
}
function KnowledgeLinkList({ links }: { links: readonly WorkspaceKnowledgeLink[] }) {
  return <ul className="mt-4 space-y-3">{links.map((link) => <li key={`${link.href}-${link.label}`}><Link href={link.href} className="group block rounded-xl border border-slate-200 bg-white p-3 transition hover:border-emerald-300 hover:bg-emerald-50/40 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-600"><span className="flex items-start justify-between gap-3"><span><span className="block text-sm font-bold text-slate-950">{link.label}</span><span className="mt-1 block text-xs leading-5 text-slate-600">{link.description}</span></span><span aria-hidden="true" className="text-emerald-700">→</span></span></Link></li>)}</ul>;
}
function KnowledgePanel({ moleculeId }: { moleculeId: string }) {
  const molecule = getWorkspaceMolecule(moleculeId); const { knowledge } = molecule;
  const lessons = requireRelationshipPresentation("molecule:recommended-lessons");
  const reagents = requireRelationshipPresentation("molecule:common-reagents");
  const labs = requireRelationshipPresentation("molecule:practice-tools");
  const reactions = requireRelationshipPresentation("molecule:common-reactions");
  return <section className="mt-8" aria-labelledby="workspace-knowledge-heading"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-700">Contextual chemistry</p><h3 id="workspace-knowledge-heading" className="mt-1 text-2xl font-bold text-slate-950">Chemistry around {molecule.name}</h3></div><p className="max-w-xl text-sm leading-6 text-slate-600">These links are selected for {molecule.name}, so each destination explains a specific structural or reactivity connection.</p></div><div className="mt-5 grid gap-4 lg:grid-cols-2 2xl:grid-cols-4">
    <article className="rounded-2xl border border-violet-200 bg-violet-50/60 p-5"><p className="text-xs font-bold uppercase tracking-[0.14em] text-violet-700">Structural identity</p><h4 className="mt-2 text-xl font-bold text-violet-950">{knowledge.functionalGroup.label}</h4><p className="mt-2 text-sm leading-6 text-slate-700">{knowledge.functionalGroup.description}</p><Link href={knowledge.functionalGroup.href} className="mt-5 inline-flex rounded-xl border border-violet-300 bg-white px-4 py-2.5 text-sm font-semibold text-violet-800">Open functional-group reference →</Link>{knowledge.lessons.length ? <div className="mt-5 border-t border-violet-200 pt-4"><p className="text-xs font-bold uppercase tracking-wide text-violet-700">{lessons.heading}</p><KnowledgeLinkList links={knowledge.lessons} /></div> : null}</article>
    <article className="rounded-2xl border border-emerald-200 bg-emerald-50/60 p-5"><p className="text-xs font-bold uppercase tracking-[0.14em] text-emerald-700">{reagents.heading}</p><h4 className="mt-2 text-xl font-bold text-emerald-950">Relevant reagents</h4><p className="mt-2 text-sm leading-6 text-slate-700">{reagents.description}</p><KnowledgeLinkList links={knowledge.reagents} /><Link href="/reagents" className="mt-5 inline-flex rounded-xl border border-emerald-300 bg-white px-4 py-2.5 text-sm font-semibold text-emerald-800">Browse the reagent library →</Link></article>
    <article className="rounded-2xl border border-blue-200 bg-blue-50/60 p-5"><p className="text-xs font-bold uppercase tracking-[0.14em] text-blue-700">{labs.heading}</p><h4 className="mt-2 text-xl font-bold text-blue-950">Practise interactively</h4><p className="mt-2 text-sm leading-6 text-slate-700">{labs.description}</p><KnowledgeLinkList links={knowledge.labs} /><Link href="/lab" className="mt-5 inline-flex rounded-xl border border-blue-300 bg-white px-4 py-2.5 text-sm font-semibold text-blue-800">Browse all labs →</Link></article>
    <article className="rounded-2xl border border-amber-200 bg-amber-50/60 p-5"><p className="text-xs font-bold uppercase tracking-[0.14em] text-amber-700">{reactions.heading}</p><h4 className="mt-2 text-xl font-bold text-amber-950">Compare pathways</h4><p className="mt-2 text-sm leading-6 text-slate-700">{reactions.description}</p><KnowledgeLinkList links={knowledge.reactions} /><Link href="/reactions" className="mt-5 inline-flex rounded-xl border border-amber-300 bg-white px-4 py-2.5 text-sm font-semibold text-amber-900">Open Reaction Explorer →</Link></article>
  </div></section>;
}

export function OverviewWorkspaceTool() {
  const { snapshot } = useWorkspace(); const molecule = getWorkspaceMolecule(snapshot.moleculeId); const molarMass = calculateMolarMass(molecule.formula);
  return <section className="p-6" role="tabpanel"><p className="text-sm font-bold uppercase tracking-[0.16em] text-emerald-700">Synchronized document</p><h2 className="mt-2 text-3xl font-bold text-slate-950">{molecule.name}</h2><div className="mt-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-6 text-center font-mono text-3xl font-bold text-emerald-950">{molecule.condensedFormula}</div><p className="mt-5 max-w-3xl leading-7 text-slate-600">{molecule.summary}</p><dl className="mt-6 grid gap-4 sm:grid-cols-3"><div className="rounded-xl border border-slate-200 p-4"><dt className="text-xs font-bold uppercase text-slate-500">Formula</dt><dd className="mt-2 font-mono text-lg font-bold">{molecule.formula}</dd></div><div className="rounded-xl border border-slate-200 p-4"><dt className="text-xs font-bold uppercase text-slate-500">Functional group</dt><dd className="mt-2 text-lg font-bold">{molecule.functionalGroup}</dd></div><div className="rounded-xl border border-slate-200 p-4"><dt className="text-xs font-bold uppercase text-slate-500">Molar mass</dt><dd className="mt-2 text-lg font-bold">{molarMass.toFixed(4)} g/mol</dd></div></dl><KnowledgePanel moleculeId={molecule.id} /></section>;
}
export function SpectraWorkspaceTool() { const { snapshot } = useWorkspace(); const molecule = getWorkspaceMolecule(snapshot.moleculeId); return <section className="p-6" role="tabpanel"><p className="text-sm font-bold uppercase tracking-[0.16em] text-cyan-700">Spectroscopy handoff</p><h2 className="mt-2 text-2xl font-bold text-slate-950">{molecule.name} spectral evidence</h2>{molecule.spectroscopyCompoundId ? <><p className="mt-3 max-w-2xl leading-7 text-slate-600">Open the canonical ¹H NMR, ¹³C NMR, IR, and mass-spectrometry dataset and link structure with signals.</p><div className="mt-6"><ToolLink href={`/lab/spectroscopy?compound=${molecule.spectroscopyCompoundId}`}>Open linked spectroscopy →</ToolLink></div></> : <p className="mt-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-amber-900">No curated spectrum is published for this molecule yet.</p>}</section>; }
export function ReactionWorkspaceTool() { const { snapshot } = useWorkspace(); const molecule = getWorkspaceMolecule(snapshot.moleculeId); return <section className="p-6" role="tabpanel"><p className="text-sm font-bold uppercase tracking-[0.16em] text-violet-700">Reaction workflow</p><h2 className="mt-2 text-2xl font-bold text-slate-950">Transform {molecule.name}</h2><p className="mt-3 max-w-2xl leading-7 text-slate-600">Carry this molecule into prediction, synthesis, or its closest mechanism context.</p><div className="mt-6 flex flex-wrap gap-3"><ToolLink href="/lab/reaction-prediction">Open prediction & synthesis →</ToolLink>{molecule.mechanismHref ? <Link href={molecule.mechanismHref} className="inline-flex rounded-xl border border-violet-300 px-4 py-2.5 text-sm font-semibold text-violet-800">Study the reaction mechanism →</Link> : null}<Link href="/reactions" className="inline-flex rounded-xl border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700">Compare reactions →</Link></div></section>; }
export function CalculationsWorkspaceTool() { const { snapshot, setAmountMmol } = useWorkspace(); const molecule = getWorkspaceMolecule(snapshot.moleculeId); const molarMass = calculateMolarMass(molecule.formula); const mass = snapshot.amountMmol / 1000 * molarMass; return <section className="p-6" role="tabpanel"><p className="text-sm font-bold uppercase tracking-[0.16em] text-blue-700">Quantitative context</p><h2 className="mt-2 text-2xl font-bold text-slate-950">Scale {molecule.name}</h2><label className="mt-6 block max-w-sm text-sm font-semibold text-slate-800">Amount (mmol)<input type="number" min="0" step="0.1" value={snapshot.amountMmol} onChange={(event) => setAmountMmol(Number(event.target.value))} className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3" /></label><dl className="mt-6 grid gap-4 sm:grid-cols-3"><div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><dt>Molar mass</dt><dd className="mt-2 text-xl font-bold">{molarMass.toFixed(4)} g/mol</dd></div><div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><dt>Amount</dt><dd className="mt-2 text-xl font-bold">{snapshot.amountMmol.toFixed(2)} mmol</dd></div><div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><dt>Required mass</dt><dd className="mt-2 text-xl font-bold">{mass.toFixed(4)} g</dd></div></dl></section>; }
export function NotesWorkspaceTool() { const { snapshot, setNotes } = useWorkspace(); const molecule = getWorkspaceMolecule(snapshot.moleculeId); return <section className="p-6" role="tabpanel"><p className="text-sm font-bold uppercase tracking-[0.16em] text-amber-700">Workspace notebook</p><h2 className="mt-2 text-2xl font-bold text-slate-950">Notes for {molecule.name}</h2><textarea aria-label="Workspace notes" value={snapshot.notes} onChange={(event) => setNotes(event.target.value)} placeholder="Record assignments, mechanism ideas, calculations, or questions…" className="mt-5 min-h-72 w-full rounded-2xl border border-slate-300 p-4 leading-7" /><p className="mt-2 text-xs text-slate-500">Saved automatically in this browser.</p></section>; }
