import { defineReaction } from "../reaction-types";

export const antiDihydroxylation = defineReaction({
  id: "anti-dihydroxylation",
  aliases: ["alkene anti dihydroxylation", "epoxide hydrolysis sequence"],
  featureId: "anti-dihydroxylation",
  substrateFunctionalGroupIds: ["alkene"],
  productFunctionalGroupIds: ["alcohol"],
  reagentIds: ["mcpba", "sulfuric-acid"],
  capabilities: { explorer: true, mechanism: true, prediction: true, retrosynthesis: true, workspace: true },
  title: "Anti dihydroxylation",
  shortTitle: "Anti dihydroxylation",
  description: "Epoxidation followed by acid-catalysed hydrolysis converts an alkene into an anti vicinal diol.",
  family: "Alkene oxidation",
  mechanismId: "anti-dihydroxylation",
  mechanismClass: "Epoxide opening",
  substrate: "Alkene",
  product: "Vicinal anti diol",
  reagents: ["1. mCPBA", "2. H₃O⁺, H₂O"],
  conditions: ["Epoxidation followed by aqueous acid"],
  steps: "Stepwise",
  intermediate: "Protonated epoxide",
  selectivity: {
    regioselectivity: "Acidic epoxide opening favours attack at the more substituted carbon when unsymmetrical",
    stereochemistry: "Anti opening gives anti vicinal diol",
    rearrangements: "No classical carbocation rearrangement",
  },
  keyIdea: "Backside attack on the activated epoxide inverts the attacked carbon and creates the anti relationship between the two OH groups.",
  competingReactionIds: ["syn-dihydroxylation"],
  relatedReactionIds: ["epoxidation"],
  prerequisiteNodeIds: ["lesson:formal-charge", "lesson:chemical-bonding"],
  mechanismHref: "/lab/anti-dihydroxylation",
  keywords: ["alkene", "anti diol", "epoxide opening", "mCPBA", "acid hydrolysis"],
});
