import { defineReaction } from "../reaction-types";

export const e1 = defineReaction({
    id: "e1",
    aliases: ["unimolecular elimination"],
    featureId: "e1",
    substrateFunctionalGroupIds: ["alkyl-halide"],
    productFunctionalGroupIds: ["alkene"],
    reagentIds: [],
    capabilities: { explorer: true, mechanism: true, prediction: true, retrosynthesis: true, workspace: true },
    title: "E1 elimination",
    shortTitle: "E1",
    description: "A stepwise elimination that forms a carbocation before loss of a beta proton.",
    family: "Elimination",
    mechanismClass: "Carbocation",
    substrate: "Tertiary or resonance-stabilised alkyl halide",
    product: "Alkene",
    reagents: ["Weak base", "Polar protic solvent"],
    conditions: ["Heat often favours elimination"],
    steps: "Stepwise",
    intermediate: "Carbocation",
    selectivity: {
      regioselectivity: "Usually Zaitsev product",
      stereochemistry: "Not stereospecific",
      rearrangements: "Possible",
    },
    keyIdea: "The same carbocation-forming step as SN1 is followed by deprotonation instead of nucleophile capture.",
    competingReactionIds: ["sn1", "e2"],
    relatedReactionIds: ["sn1"],
    prerequisiteNodeIds: ["lesson:chemical-bonding", "lesson:resonance"],
    mechanismHref: "/lab/e1-mechanism",
    keywords: ["elimination", "carbocation", "zaitsev", "unimolecular"],
  });
