import { defineReaction } from "../reaction-types";

export const epoxidation = defineReaction({
  id: "epoxidation",
  aliases: ["alkene epoxidation", "peracid epoxidation"],
  featureId: "epoxidation",
  substrateFunctionalGroupIds: ["alkene"],
  productFunctionalGroupIds: ["epoxide"],
  reagentIds: ["mcpba"],
  capabilities: { explorer: true, mechanism: true, prediction: true, retrosynthesis: true, workspace: true },
  title: "Alkene epoxidation",
  shortTitle: "Epoxidation",
  description: "Concerted oxygen transfer from a peracid converts an alkene directly into an epoxide.",
  family: "Alkene oxidation",
  mechanismId: "epoxidation",
  mechanismClass: "Peracid concerted",
  substrate: "Alkene",
  product: "Epoxide",
  reagents: ["mCPBA or another peracid"],
  conditions: ["Aprotic organic solvent", "Moderate temperature"],
  steps: "Concerted",
  intermediate: "No discrete intermediate; cyclic transition state",
  selectivity: {
    regioselectivity: "Not usually applicable",
    stereochemistry: "Stereospecific retention of alkene geometry in the epoxide",
    rearrangements: "Not possible because no carbocation forms",
  },
  keyIdea: "The alkene π bond and peracid O–O system reorganise in one concerted oxygen-transfer event.",
  competingReactionIds: ["syn-dihydroxylation"],
  relatedReactionIds: ["anti-dihydroxylation", "halogenation"],
  prerequisiteNodeIds: ["lesson:chemical-bonding", "lesson:formal-charge"],
  mechanismHref: "/lab/epoxidation",
  keywords: ["alkene", "epoxide", "mCPBA", "peracid", "concerted oxidation"],
});
