import { defineReaction } from "../reaction-types";

export const hydrogenation = defineReaction({
    id: "hydrogenation",
    aliases: ["catalytic alkene reduction"],
    featureId: "hydrogenation",
    substrateFunctionalGroupIds: ["alkene"],
    productFunctionalGroupIds: [],
    reagentIds: ["hydrogen-palladium"],
    capabilities: { explorer: true, mechanism: true, prediction: true, retrosynthesis: true, workspace: true },
    title: "Catalytic hydrogenation",
    shortTitle: "Hydrogenation",
    description: "Reduction of an alkene on a metal surface using molecular hydrogen.",
    family: "Reduction",
    mechanismId: "hydrogenation",
    mechanismClass: "Surface catalysis",
    substrate: "Alkene",
    product: "Alkane",
    reagents: ["H₂", "Pd, Pt, or Ni catalyst"],
    conditions: ["Metal surface", "Hydrogen atmosphere"],
    steps: "Stepwise",
    intermediate: "Surface-bound species",
    selectivity: {
      regioselectivity: "Not applicable",
      stereochemistry: "Syn addition",
      rearrangements: "Not possible",
    },
    keyIdea: "Both hydrogens are delivered from the catalyst surface to the same face of the alkene.",
    competingReactionIds: [],
    relatedReactionIds: ["halogenation"],
    prerequisiteNodeIds: ["lesson:chemical-bonding"],
    mechanismHref: "/lab/hydrogenation",
    keywords: ["reduction", "alkene", "syn addition", "catalyst"],
  });
