import { defineReaction } from "../reaction-types";

export const hydroboration_oxidation = defineReaction({
    id: "hydroboration-oxidation",
    aliases: ["hydroboration oxidation"],
    featureId: "hydroboration-oxidation",
    substrateFunctionalGroupIds: ["alkene"],
    productFunctionalGroupIds: ["alcohol"],
    reagentIds: ["borane-peroxide"],
    capabilities: { explorer: true, mechanism: true, prediction: true, retrosynthesis: true, workspace: true },
    title: "Hydroboration–oxidation",
    shortTitle: "Hydroboration",
    description: "Two-step conversion of an alkene to an anti-Markovnikov alcohol.",
    family: "Alkene addition",
    mechanismClass: "Organoborane",
    substrate: "Alkene",
    product: "Alcohol",
    reagents: ["1. BH₃ or 9-BBN", "2. H₂O₂, OH⁻"],
    conditions: ["Anhydrous hydroboration then oxidative workup"],
    steps: "Stepwise",
    intermediate: "Organoborane",
    selectivity: {
      regioselectivity: "Anti-Markovnikov",
      stereochemistry: "Syn addition",
      rearrangements: "Not possible",
    },
    keyIdea: "Concerted hydroboration places boron at the less substituted carbon before oxidation replaces B with OH.",
    competingReactionIds: ["hydration", "oxymercuration-demercuration"],
    relatedReactionIds: ["radical-hbr"],
    prerequisiteNodeIds: ["lesson:chemical-bonding", "lesson:hybridization"],
    mechanismHref: "/lab/hydroboration-oxidation",
    keywords: ["alkene", "anti markovnikov", "syn addition", "alcohol"],
  });
