import { defineReaction } from "../reaction-types";

export const oxidativeCleavage = defineReaction({
  id: "oxidative-cleavage",
  aliases: ["permanganate oxidative cleavage", "hot KMnO4 alkene cleavage"],
  featureId: "oxidative-cleavage",
  substrateFunctionalGroupIds: ["alkene"],
  productFunctionalGroupIds: ["carbonyl", "carboxylic-acid"],
  reagentIds: ["potassium-permanganate"],
  capabilities: { explorer: true, mechanism: true, prediction: true, retrosynthesis: true, workspace: true },
  title: "Oxidative cleavage of alkenes",
  shortTitle: "Oxidative cleavage",
  description: "Strong permanganate oxidation cleaves C=C bonds; alkene carbons bearing hydrogen are oxidised beyond aldehydes to carboxylic acids, while fully substituted carbons give ketones.",
  family: "Alkene oxidation",
  mechanismId: "oxidative-cleavage",
  mechanismClass: "Permanganate oxidation",
  substrate: "Alkene",
  product: "Ketones, carboxylic acids, and for terminal CH₂ carbons ultimately CO₂ under vigorous conditions",
  reagents: ["Hot, concentrated KMnO₄", "Oxidative workup"],
  conditions: ["Strongly oxidative conditions", "Often heat"],
  steps: "Stepwise",
  intermediate: "Manganate ester / vicinal oxidation intermediates",
  selectivity: {
    regioselectivity: "Cleavage occurs at the C=C bond",
    stereochemistry: "Not retained after bond cleavage",
    rearrangements: "Not a carbocation pathway",
  },
  keyIdea: "After cleavage, classify each former alkene carbon by whether it bore hydrogen: ketone if none, carboxylic acid if one, and further oxidation for terminal CH₂ fragments.",
  competingReactionIds: ["ozonolysis"],
  relatedReactionIds: ["syn-dihydroxylation"],
  prerequisiteNodeIds: ["lesson:chemical-bonding"],
  mechanismHref: "/lab/oxidative-cleavage",
  keywords: ["alkene", "KMnO4", "oxidative cleavage", "ketone", "carboxylic acid"],
});
