import { defineReaction } from "../reaction-types";

export const ozonolysis = defineReaction({
  id: "ozonolysis",
  aliases: ["reductive ozonolysis", "alkene ozonolysis"],
  featureId: "ozonolysis",
  substrateFunctionalGroupIds: ["alkene"],
  productFunctionalGroupIds: ["carbonyl"],
  reagentIds: ["ozone", "zinc"],
  capabilities: { explorer: true, mechanism: true, prediction: true, retrosynthesis: true, workspace: true },
  title: "Reductive ozonolysis",
  shortTitle: "Ozonolysis",
  description: "Ozone cleaves an alkene through ozonide chemistry; reductive workup gives aldehydes and ketones that reveal the original C=C substitution pattern.",
  family: "Alkene oxidation",
  mechanismId: "ozonolysis",
  mechanismClass: "Ozonide cleavage",
  substrate: "Alkene",
  product: "Aldehyde and/or ketone fragments",
  reagents: ["1. O₃", "2. Zn/H₂O or Me₂S"],
  conditions: ["Low-temperature ozonation is common", "Reductive workup"],
  steps: "Stepwise",
  intermediate: "Molozonide and ozonide",
  selectivity: {
    regioselectivity: "Each original alkene carbon becomes a carbonyl carbon",
    stereochemistry: "Alkene E/Z geometry is lost on cleavage",
    rearrangements: "No carbocation rearrangement",
  },
  keyIdea: "Disconnect the C=C bond mentally and place an oxygen on each alkene carbon to predict the reductive ozonolysis products.",
  competingReactionIds: ["oxidative-cleavage"],
  relatedReactionIds: ["epoxidation", "syn-dihydroxylation"],
  prerequisiteNodeIds: ["lesson:formal-charge", "lesson:chemical-bonding"],
  mechanismHref: "/lab/ozonolysis",
  keywords: ["alkene", "ozone", "cleavage", "aldehyde", "ketone", "ozonide"],
});
