import { defineReaction } from "../reaction-types";

export const sn1 = defineReaction({
    id: "sn1",
    aliases: ["unimolecular nucleophilic substitution"],
    featureId: "sn1",
    substrateFunctionalGroupIds: ["alkyl-halide"],
    productFunctionalGroupIds: [],
    reagentIds: [],
    capabilities: { explorer: true, mechanism: true, prediction: true, retrosynthesis: true, workspace: true },
    title: "SN1 substitution",
    shortTitle: "SN1",
    description: "A stepwise substitution that forms a carbocation before nucleophile capture.",
    family: "Substitution",
    mechanismClass: "Carbocation",
    substrate: "Tertiary or resonance-stabilised alkyl halide",
    product: "Substitution product",
    reagents: ["Weak or neutral nucleophile", "Polar protic solvent"],
    conditions: ["Ionising solvent", "Moderate heat"],
    steps: "Stepwise",
    intermediate: "Carbocation",
    selectivity: {
      regioselectivity: "Controlled by carbocation stability",
      stereochemistry: "Often racemisation at the reacting centre",
      rearrangements: "Possible",
    },
    keyIdea: "Leaving-group departure is rate-determining; nucleophile strength is less important than carbocation stability.",
    competingReactionIds: ["e1", "sn2"],
    relatedReactionIds: ["e1"],
    prerequisiteNodeIds: ["lesson:chemical-bonding", "lesson:resonance"],
    mechanismHref: "/lab/sn1-mechanism",
    keywords: ["substitution", "carbocation", "racemisation", "unimolecular"],
  });
