import { defineReaction } from "../reaction-types";

export const sn2 = defineReaction({
    id: "sn2",
    aliases: ["bimolecular nucleophilic substitution"],
    featureId: "sn2",
    substrateFunctionalGroupIds: ["alkyl-halide"],
    productFunctionalGroupIds: [],
    reagentIds: ["hydroxide"],
    capabilities: { explorer: true, mechanism: true, prediction: true, retrosynthesis: true, workspace: true },
    title: "SN2 substitution",
    shortTitle: "SN2",
    description: "A one-step backside attack in which bond formation and leaving-group departure occur together.",
    family: "Substitution",
    mechanismId: "sn2",
    mechanismClass: "Concerted",
    substrate: "Methyl or primary alkyl halide",
    product: "Substitution product",
    reagents: ["Strong nucleophile", "Polar aprotic solvent"],
    conditions: ["Low steric hindrance"],
    steps: "Concerted",
    intermediate: "None",
    selectivity: {
      regioselectivity: "Attack occurs at the electrophilic carbon",
      stereochemistry: "Walden inversion",
      rearrangements: "Not possible",
    },
    keyIdea: "Steric accessibility and nucleophile strength control the rate of backside attack.",
    competingReactionIds: ["e2", "sn1"],
    relatedReactionIds: ["e2"],
    prerequisiteNodeIds: ["lesson:chemical-bonding", "lesson:resonance"],
    mechanismHref: "/lab/sn2-mechanism",
    keywords: ["substitution", "backside attack", "inversion", "bimolecular"],
  });
