import { defineReaction } from "../reaction-types";

export const synDihydroxylation = defineReaction({
  id: "syn-dihydroxylation",
  aliases: ["alkene syn dihydroxylation", "osmium tetroxide dihydroxylation"],
  featureId: "syn-dihydroxylation",
  substrateFunctionalGroupIds: ["alkene"],
  productFunctionalGroupIds: ["alcohol"],
  reagentIds: ["osmium-tetroxide"],
  capabilities: { explorer: true, mechanism: true, prediction: true, retrosynthesis: true, workspace: true },
  title: "Syn dihydroxylation",
  shortTitle: "Syn dihydroxylation",
  description: "Osmium tetroxide converts an alkene into a vicinal diol by stereospecific syn addition through a cyclic osmate ester.",
  family: "Alkene oxidation",
  mechanismId: "syn-dihydroxylation",
  mechanismClass: "Osmate ester",
  substrate: "Alkene",
  product: "Vicinal syn diol",
  reagents: ["OsO₄", "Co-oxidant when OsO₄ is catalytic", "Aqueous workup"],
  conditions: ["Mild oxidation conditions", "Hydrolytic workup"],
  steps: "Stepwise",
  intermediate: "Cyclic osmate ester",
  selectivity: {
    regioselectivity: "Both alkene carbons receive OH",
    stereochemistry: "Syn addition; stereospecific",
    rearrangements: "Not possible",
  },
  keyIdea: "Both C–O bonds form from the same face as the alkene enters a cyclic osmate ester, fixing syn stereochemistry.",
  competingReactionIds: ["epoxidation", "anti-dihydroxylation"],
  relatedReactionIds: ["oxidative-cleavage"],
  prerequisiteNodeIds: ["lesson:chemical-bonding", "lesson:hybridization"],
  mechanismHref: "/lab/syn-dihydroxylation",
  keywords: ["alkene", "OsO4", "syn", "vicinal diol", "osmate ester"],
});
