import type { PlatformFeature } from "./feature-types";

const feature = (value: PlatformFeature): PlatformFeature => value;

export const platformFeatures = [
  feature({ id: "home", title: "Organic Chemistry Hub", description: "Interactive organic chemistry lessons, references, labs, and tools.", href: "/", kind: "site", search: { category: "Site", keywords: ["organic chemistry", "learning", "home"] }, sitemap: { priority: 1, changeFrequency: "weekly" }, smokeTest: { expectedText: { source: "Organic Chemistry Hub", flags: "i" } } }),
  feature({ id: "learn", title: "Learn organic chemistry", description: "Structured lessons covering the foundations of organic chemistry.", href: "/learn", kind: "site", search: { category: "Site", keywords: ["curriculum", "fundamentals", "lessons"] }, sitemap: { priority: 0.9, changeFrequency: "weekly" }, smokeTest: { expectedText: { source: "Learn", flags: "i" } } }),
  feature({ id: "study-dashboard", title: "Study dashboard", description: "Track progress, review due concepts, and continue your personalised study plan.", href: "/study", kind: "site", search: { category: "Site", keywords: ["progress", "streak", "review", "spaced repetition", "continue studying"] }, sitemap: { priority: 0.6 }, smokeTest: { expectedText: { source: "Study dashboard", flags: "i" } } }),
  feature({ id: "organic-chemistry-workspace", title: "Organic Chemistry Workspace", description: "Keep a molecule synchronized across spectra, reaction planning, calculations, references, and notes.", href: "/workspace", kind: "site", search: { category: "Site", keywords: ["workspace", "workbench", "molecule", "spectroscopy", "synthesis", "calculations", "notes"] }, sitemap: { priority: 0.7 }, smokeTest: { expectedText: { source: "Organic Chemistry Workspace", flags: "i" } } }),
  feature({ id: "reaction-explorer", title: "Interactive reaction explorer", description: "Filter and compare substitution, elimination, and alkene addition reactions.", href: "/reactions", kind: "reference", search: { category: "Reference", keywords: ["reaction comparison", "SN1", "SN2", "E1", "E2", "alkene addition", "selectivity"] }, sitemap: { priority: 0.7 }, smokeTest: { expectedText: { source: "Compare mechanisms", flags: "i" } } }),

  feature({ id: "lab", title: "Interactive chemistry lab", description: "Mechanism players, molecular explorers, builders, and trainers.", href: "/lab", kind: "lab", search: { category: "Lab", keywords: ["interactive", "practice", "tools"] }, sitemap: { priority: 0.9 }, smokeTest: { expectedText: { source: "Lab", flags: "i" } } }),
  feature({ id: "sn1", title: "SN1 mechanism", description: "Explore the stepwise unimolecular nucleophilic substitution mechanism.", href: "/lab/sn1-mechanism", kind: "mechanism", search: { category: "Mechanism", keywords: ["substitution", "carbocation", "leaving group"] }, sitemap: { priority: 0.7 } }),
  feature({ id: "sn2", title: "SN2 mechanism", description: "Follow backside attack and concerted leaving-group departure.", href: "/lab/sn2-mechanism", kind: "mechanism", search: { category: "Mechanism", keywords: ["substitution", "backside attack", "inversion"] }, sitemap: { priority: 0.7 }, smokeTest: { expectedText: { source: "SN2", flags: "i" } } }),
  feature({ id: "e1", title: "E1 mechanism", description: "Study unimolecular elimination through a carbocation intermediate.", href: "/lab/e1-mechanism", kind: "mechanism", search: { category: "Mechanism", keywords: ["elimination", "carbocation", "alkene"] }, sitemap: { priority: 0.7 } }),
  feature({ id: "e2", title: "E2 mechanism", description: "Study concerted bimolecular elimination and anti-periplanar geometry.", href: "/lab/e2-mechanism", kind: "mechanism", search: { category: "Mechanism", keywords: ["elimination", "anti periplanar", "alkene"] }, sitemap: { priority: 0.7 } }),
  feature({ id: "electrophilic-addition", title: "Electrophilic addition", description: "Explore electron flow during addition reactions of alkenes.", href: "/lab/electrophilic-addition", kind: "mechanism", search: { category: "Mechanism", keywords: ["alkene", "pi bond", "addition"] }, sitemap: { priority: 0.7 } }),
  feature({ id: "hybridization-lab", title: "Hybridization explorer", description: "Connect hybridization, orbital geometry, and sigma and pi bonding.", href: "/lab/hybridization", kind: "lab", search: { category: "Lab", keywords: ["sp", "sp2", "sp3", "geometry"] }, sitemap: { priority: 0.7 }, smokeTest: { expectedText: { source: "Hybridization", flags: "i" } } }),
  feature({ id: "molecular-geometry", title: "Molecular geometry explorer", description: "Explore molecular shapes and electron-domain geometry.", href: "/lab/molecular-geometry", kind: "lab", search: { category: "Lab", keywords: ["vsepr", "shape", "bond angle"] }, sitemap: { priority: 0.7 } }),
  feature({ id: "molecular-polarity", title: "Molecular polarity explorer", description: "Relate bond dipoles and molecular geometry to overall polarity.", href: "/lab/molecular-polarity", kind: "lab", search: { category: "Lab", keywords: ["dipole", "polar", "nonpolar"] }, sitemap: { priority: 0.7 } }),
  feature({ id: "functional-groups-lab", title: "Functional groups explorer", description: "Identify and compare common organic functional groups.", href: "/lab/functional-groups", kind: "lab", search: { category: "Lab", keywords: ["alcohol", "ketone", "aldehyde", "amine"] }, sitemap: { priority: 0.7 } }),
  feature({ id: "spectroscopy-lab", title: "Interactive spectroscopy lab", description: "Link molecular structure to realistic simulated 1H NMR, 13C NMR, IR, and mass spectra.", href: "/lab/spectroscopy", kind: "lab", search: { category: "Lab", keywords: ["spectroscopy", "NMR", "IR", "mass spectrometry", "peak assignment", "chemical shift"] }, sitemap: { priority: 0.8 }, smokeTest: { expectedText: { source: "Interactive Spectroscopy Lab", flags: "i" } } }),
  feature({ id: "reaction-prediction-lab", title: "Reaction prediction and synthesis lab", description: "Predict major products, explain selectivity, and build multi-step synthesis routes.", href: "/lab/reaction-prediction", kind: "lab", search: { category: "Lab", keywords: ["reaction prediction", "synthesis", "major product", "regioselectivity", "stereochemistry", "reagents"] }, sitemap: { priority: 0.8 }, smokeTest: { expectedText: { source: "Reaction Prediction & Synthesis", flags: "i" } } }),
  feature({ id: "retrosynthesis-planner", title: "Retrosynthesis planner", description: "Work backwards from target molecules, compare ranked disconnections, and validate routes with forward mechanisms.", href: "/lab/retrosynthesis", kind: "lab", search: { category: "Lab", keywords: ["retrosynthesis", "disconnection", "route planning", "precursors", "starting materials", "synthesis"] }, sitemap: { priority: 0.8 }, smokeTest: { expectedText: { source: "Retrosynthesis Planner", flags: "i" } } }),

  ...[
    ["bond-playground", "/lab/bond-playground"],
    ["curved-arrow-designer", "/lab/curved-arrow-designer"],
    ["curved-arrow-playground", "/lab/curved-arrow-playground"],
    ["halogenation", "/lab/halogenation"],
    ["hydration", "/lab/hydration"],
    ["hydroboration-oxidation", "/lab/hydroboration-oxidation"],
    ["hydrogenation", "/lab/hydrogenation"],
    ["hydrohalogenation", "/lab/hydrohalogenation"],
    ["lab-lewis-structure-builder", "/lab/lewis-structure-builder"],
    ["molecule-playground", "/lab/molecule-playground"],
    ["oxymercuration-demercuration", "/lab/oxymercuration-demercuration"],
    ["radical-hbr-addition", "/lab/radical-hbr-addition"],
    ["skeletal-molecule-builder", "/lab/skeletal-molecule-builder"],
  ].map(([id, href]) => feature({ id, title: id.replaceAll("-", " "), description: `Interactive ${id.replaceAll("-", " ")} lab.`, href: href as `/${string}`, kind: "lab", sitemap: { priority: 0.7 } })),

  feature({ id: "calculators", title: "Chemistry calculators", description: "Practical calculators and structure-building tools.", href: "/calculators", kind: "calculator", search: { category: "Calculator", keywords: ["tools", "builder"] }, sitemap: { priority: 0.7 } }),
  feature({ id: "molecular-weight-calculator", title: "Molecular weight calculator", description: "Calculate molar mass and elemental composition from a molecular formula.", href: "/calculators/molecular-weight", kind: "calculator", search: { category: "Calculator", keywords: ["molar mass", "molecular formula", "atomic weight", "composition"] }, sitemap: { priority: 0.7 }, smokeTest: { expectedText: { source: "Molecular weight calculator", flags: "i" } } }),
  feature({ id: "molarity-calculator", title: "Molarity and solution preparation", description: "Solve concentration, amount, solute mass, or solution volume.", href: "/calculators/molarity", kind: "calculator", search: { category: "Calculator", keywords: ["molarity", "concentration", "solution", "moles", "mass"] }, sitemap: { priority: 0.7 }, smokeTest: { expectedText: { source: "Molarity and solution preparation", flags: "i" } } }),
  feature({ id: "dilution-calculator", title: "Dilution calculator", description: "Plan stock-solution dilutions with C1V1 = C2V2.", href: "/calculators/dilution", kind: "calculator", search: { category: "Calculator", keywords: ["dilution", "stock solution", "C1V1", "C2V2"] }, sitemap: { priority: 0.7 }, smokeTest: { expectedText: { source: "Dilution calculator", flags: "i" } } }),
  feature({ id: "stoichiometry-calculator", title: "Stoichiometry calculator", description: "Convert reactant amount to expected product amount using mole ratios.", href: "/calculators/stoichiometry", kind: "calculator", search: { category: "Calculator", keywords: ["stoichiometry", "mole ratio", "reaction scale", "balanced equation"] }, sitemap: { priority: 0.7 }, smokeTest: { expectedText: { source: "Stoichiometry calculator", flags: "i" } } }),
  feature({ id: "limiting-reagent-calculator", title: "Limiting reagent calculator", description: "Identify the limiting reactant and theoretical product yield.", href: "/calculators/limiting-reagent", kind: "calculator", search: { category: "Calculator", keywords: ["limiting reagent", "excess reagent", "theoretical yield"] }, sitemap: { priority: 0.7 }, smokeTest: { expectedText: { source: "Limiting reagent calculator", flags: "i" } } }),
  feature({ id: "percent-yield-calculator", title: "Percent yield calculator", description: "Compare actual and theoretical product yields.", href: "/calculators/percent-yield", kind: "calculator", search: { category: "Calculator", keywords: ["percent yield", "actual yield", "theoretical yield"] }, sitemap: { priority: 0.7 }, smokeTest: { expectedText: { source: "Percent yield calculator", flags: "i" } } }),
  feature({ id: "lewis-builder", title: "Lewis structure builder", description: "Build and check Lewis structures interactively.", href: "/calculators/lewis-structure-builder", kind: "calculator", search: { category: "Calculator", keywords: ["electrons", "formal charge", "octet"] }, sitemap: { priority: 0.7 }, smokeTest: { expectedText: { source: "Lewis", flags: "i" } } }),

  feature({ id: "functional-groups", title: "Functional groups reference", description: "Reference material for common organic functional groups.", href: "/functional-groups", kind: "reference", search: { category: "Reference", keywords: ["classification", "structure", "nomenclature"] }, sitemap: { priority: 0.6 } }),
  feature({ id: "named-reactions", title: "Named reactions", description: "Reference collection for important named organic reactions.", href: "/named-reactions", kind: "reference", search: { category: "Reference", keywords: ["reaction", "mechanism", "synthesis"] }, sitemap: { priority: 0.6 } }),
  feature({ id: "reagents", title: "Reagents", description: "Reference guides for common organic chemistry reagents.", href: "/reagents", kind: "reference", search: { category: "Reference", keywords: ["oxidation", "reduction", "conditions"] }, sitemap: { priority: 0.6 } }),
  feature({ id: "resources", title: "Resources", description: "Study resources, references, and supporting material.", href: "/resources", kind: "reference", search: { category: "Reference", keywords: ["study", "books", "links"] }, sitemap: { priority: 0.6 } }),
  feature({ id: "about", title: "About Organic Chemistry Hub", description: "Learn about the project, its goals, and its approach.", href: "/about", kind: "site", search: { category: "Site", keywords: ["project", "mission"] }, sitemap: { priority: 0.6 } }),
  feature({ id: "editorial-policy", title: "Editorial policy", description: "How educational content is researched, reviewed, and maintained.", href: "/editorial-policy", kind: "site", search: { category: "Site", keywords: ["quality", "sources", "accuracy"] }, sitemap: { priority: 0.6 } }),
  feature({ id: "contact", title: "Contact", description: "Contact Organic Chemistry Hub.", href: "/contact", kind: "site", sitemap: { priority: 0.5 } }),
] as const satisfies readonly PlatformFeature[];
