import { getSynthesisStructure } from "@/content/synthesis";
import type { RetrosynthesisRule, RetrosynthesisTarget } from "./retrosynthesis-types";

export const retrosynthesisRules: readonly RetrosynthesisRule[] = [
  {
    id: "retro-primary-alcohol-from-alkene",
    title: "Disconnect the primary alcohol to an alkene",
    productId: "1-propanol",
    precursorIds: ["propene"],
    forwardReagents: "1. BH₃·THF  2. H₂O₂, OH⁻",
    reactionId: "hydroboration-oxidation",
    mechanismHref: "/lab/hydroboration-oxidation",
    rationale: "Hydroboration–oxidation installs OH at the less substituted carbon without a carbocation.",
    selectivity: "Anti-Markovnikov alcohol; syn addition overall.",
    reliability: 0.94,
    difficulty: 1,
    risk: "low",
  },
  {
    id: "retro-secondary-alcohol-from-alkene",
    title: "Disconnect the secondary alcohol to an alkene",
    productId: "2-propanol",
    precursorIds: ["propene"],
    forwardReagents: "H₂O, H₂SO₄",
    reactionId: "hydration",
    mechanismHref: "/lab/hydration",
    rationale: "Acid-catalysed hydration gives the Markovnikov alcohol through a carbocation pathway.",
    selectivity: "Markovnikov; rearrangements matter for less symmetric substrates.",
    reliability: 0.82,
    difficulty: 1,
    risk: "medium",
  },
  {
    id: "retro-primary-bromide-from-alkene",
    title: "Disconnect the primary bromide to an alkene",
    productId: "1-bromopropane",
    precursorIds: ["propene"],
    forwardReagents: "HBr, ROOR",
    reactionId: "radical-hbr",
    mechanismHref: "/lab/radical-hbr-addition",
    rationale: "The peroxide-promoted radical chain reverses the usual HBr regiochemistry.",
    selectivity: "Anti-Markovnikov; specific to HBr among common hydrogen halides.",
    reliability: 0.86,
    difficulty: 2,
    risk: "medium",
  },
  {
    id: "retro-secondary-bromide-from-alkene",
    title: "Disconnect the secondary bromide to an alkene",
    productId: "2-bromopropane",
    precursorIds: ["propene"],
    forwardReagents: "HBr",
    reactionId: "hydrohalogenation",
    mechanismHref: "/lab/hydrohalogenation",
    rationale: "Ionic HBr addition proceeds through the more stable secondary carbocation.",
    selectivity: "Markovnikov; not stereospecific.",
    reliability: 0.9,
    difficulty: 1,
    risk: "low",
  },
  {
    id: "retro-dibromide-from-alkene",
    title: "Disconnect the vicinal dibromide to an alkene",
    productId: "1,2-dibromopropane",
    precursorIds: ["propene"],
    forwardReagents: "Br₂",
    reactionId: "halogenation",
    mechanismHref: "/lab/halogenation",
    rationale: "Bromination proceeds through a bridged bromonium ion and anti opening.",
    selectivity: "Anti vicinal addition without carbocation rearrangement.",
    reliability: 0.96,
    difficulty: 1,
    risk: "low",
  },
  {
    id: "retro-alkene-from-secondary-bromide",
    title: "Form the alkene by dehydrohalogenation",
    productId: "propene",
    precursorIds: ["2-bromopropane"],
    forwardReagents: "NaOEt, EtOH, heat",
    reactionId: "e2",
    mechanismHref: "/lab/e2-mechanism",
    rationale: "A strong base removes a β hydrogen while bromide leaves in one concerted step.",
    selectivity: "Requires an anti-periplanar β hydrogen and leaving group.",
    reliability: 0.88,
    difficulty: 2,
    risk: "medium",
  },
  {
    id: "retro-primary-alcohol-from-bromide",
    title: "Disconnect the alcohol to a primary bromide",
    productId: "1-propanol",
    precursorIds: ["1-bromopropane"],
    forwardReagents: "NaOH, aqueous",
    reactionId: "sn2",
    mechanismHref: "/lab/sn2-mechanism",
    rationale: "Hydroxide displaces bromide efficiently at an unhindered primary carbon.",
    selectivity: "SN2 substitution; inversion is relevant for stereogenic substrates.",
    reliability: 0.91,
    difficulty: 1,
    risk: "low",
  },
  {
    id: "retro-primary-bromide-from-alcohol",
    title: "Disconnect the bromide to a primary alcohol",
    productId: "1-bromopropane",
    precursorIds: ["1-propanol"],
    forwardReagents: "PBr₃",
    reactionId: "sn2",
    mechanismHref: "/lab/sn2-mechanism",
    rationale: "PBr₃ converts a poor hydroxyl leaving group into a substitution-ready intermediate.",
    selectivity: "Works well for primary and secondary alcohols; avoids carbocation rearrangement.",
    reliability: 0.93,
    difficulty: 2,
    risk: "low",
  },
];

export const retrosynthesisTargets: readonly RetrosynthesisTarget[] = [
  {
    id: "retro-1-propanol",
    title: "Plan a synthesis of 1-propanol",
    difficulty: "Foundation",
    targetStructureId: "1-propanol",
    availableStartingMaterialIds: ["propene", "1-bromopropane"],
    maxDepth: 3,
    recommendedRuleIds: ["retro-primary-alcohol-from-alkene"],
    learningGoal: "Compare direct alkene functionalisation with substitution-based routes.",
    hint: "Look for a reaction that installs OH at the terminal carbon in one step.",
  },
  {
    id: "retro-1-bromopropane",
    title: "Plan a synthesis of 1-bromopropane",
    difficulty: "Intermediate",
    targetStructureId: "1-bromopropane",
    availableStartingMaterialIds: ["propene", "1-propanol"],
    maxDepth: 3,
    recommendedRuleIds: ["retro-primary-bromide-from-alkene"],
    learningGoal: "Choose between radical addition and functional-group interconversion.",
    hint: "A peroxide-promoted addition reaches the terminal bromide directly.",
  },
  {
    id: "retro-1-propanol-from-secondary-bromide",
    title: "Reach 1-propanol from 2-bromopropane",
    difficulty: "Advanced",
    targetStructureId: "1-propanol",
    availableStartingMaterialIds: ["2-bromopropane"],
    maxDepth: 4,
    recommendedRuleIds: ["retro-primary-alcohol-from-alkene", "retro-alkene-from-secondary-bromide"],
    learningGoal: "Work backwards through elimination, then control alkene hydration regiochemistry.",
    hint: "The target alcohol can come from propene; now ask how propene can come from the available bromide.",
  },
];

export function requireRetrosynthesisStructure(id: string) {
  const structure = getSynthesisStructure(id);
  if (!structure) throw new Error(`Unknown retrosynthesis structure: ${id}`);
  return structure;
}
