import type { ReactionDefinition } from "./reaction-types";

export const reactions: readonly ReactionDefinition[] = [
  {
    id: "sn1",
    title: "SN1 substitution",
    shortTitle: "SN1",
    description: "A stepwise substitution that forms a carbocation before nucleophile capture.",
    family: "Substitution",
    mechanismClass: "Carbocation",
    substrate: "Tertiary or resonance-stabilised alkyl halide",
    product: "Substitution product",
    reagents: ["Weak or neutral nucleophile", "Polar protic solvent"],
    conditions: ["Ionising solvent", "Moderate heat"],
    steps: "Stepwise",
    intermediate: "Carbocation",
    selectivity: {
      regioselectivity: "Controlled by carbocation stability",
      stereochemistry: "Often racemisation at the reacting centre",
      rearrangements: "Possible",
    },
    keyIdea: "Leaving-group departure is rate-determining; nucleophile strength is less important than carbocation stability.",
    competingReactionIds: ["e1", "sn2"],
    relatedReactionIds: ["e1"],
    prerequisiteNodeIds: ["lesson:chemical-bonding", "lesson:resonance"],
    mechanismHref: "/lab/sn1-mechanism",
    keywords: ["substitution", "carbocation", "racemisation", "unimolecular"],
  },
  {
    id: "sn2",
    title: "SN2 substitution",
    shortTitle: "SN2",
    description: "A one-step backside attack in which bond formation and leaving-group departure occur together.",
    family: "Substitution",
    mechanismClass: "Concerted",
    substrate: "Methyl or primary alkyl halide",
    product: "Substitution product",
    reagents: ["Strong nucleophile", "Polar aprotic solvent"],
    conditions: ["Low steric hindrance"],
    steps: "Concerted",
    intermediate: "None",
    selectivity: {
      regioselectivity: "Attack occurs at the electrophilic carbon",
      stereochemistry: "Walden inversion",
      rearrangements: "Not possible",
    },
    keyIdea: "Steric accessibility and nucleophile strength control the rate of backside attack.",
    competingReactionIds: ["e2", "sn1"],
    relatedReactionIds: ["e2"],
    prerequisiteNodeIds: ["lesson:chemical-bonding", "lesson:resonance"],
    mechanismHref: "/lab/sn2-mechanism",
    keywords: ["substitution", "backside attack", "inversion", "bimolecular"],
  },
  {
    id: "e1",
    title: "E1 elimination",
    shortTitle: "E1",
    description: "A stepwise elimination that forms a carbocation before loss of a beta proton.",
    family: "Elimination",
    mechanismClass: "Carbocation",
    substrate: "Tertiary or resonance-stabilised alkyl halide",
    product: "Alkene",
    reagents: ["Weak base", "Polar protic solvent"],
    conditions: ["Heat often favours elimination"],
    steps: "Stepwise",
    intermediate: "Carbocation",
    selectivity: {
      regioselectivity: "Usually Zaitsev product",
      stereochemistry: "Not stereospecific",
      rearrangements: "Possible",
    },
    keyIdea: "The same carbocation-forming step as SN1 is followed by deprotonation instead of nucleophile capture.",
    competingReactionIds: ["sn1", "e2"],
    relatedReactionIds: ["sn1"],
    prerequisiteNodeIds: ["lesson:chemical-bonding", "lesson:resonance"],
    mechanismHref: "/lab/e1-mechanism",
    keywords: ["elimination", "carbocation", "zaitsev", "unimolecular"],
  },
  {
    id: "e2",
    title: "E2 elimination",
    shortTitle: "E2",
    description: "A concerted elimination in which a strong base removes a beta proton as the leaving group departs.",
    family: "Elimination",
    mechanismClass: "Concerted",
    substrate: "Alkyl halide with an accessible beta hydrogen",
    product: "Alkene",
    reagents: ["Strong base"],
    conditions: ["Anti-periplanar geometry", "Heat often favours elimination"],
    steps: "Concerted",
    intermediate: "None",
    selectivity: {
      regioselectivity: "Zaitsev or Hofmann depending on base and substrate",
      stereochemistry: "Anti-periplanar and stereospecific",
      rearrangements: "Not possible",
    },
    keyIdea: "Base strength and anti-periplanar geometry are more important than carbocation stability.",
    competingReactionIds: ["sn2", "e1"],
    relatedReactionIds: ["sn2"],
    prerequisiteNodeIds: ["lesson:chemical-bonding", "lesson:hybridization"],
    mechanismHref: "/lab/e2-mechanism",
    keywords: ["elimination", "anti periplanar", "strong base", "bimolecular"],
  },
  {
    id: "electrophilic-addition",
    title: "Electrophilic addition",
    shortTitle: "Electrophilic addition",
    description: "A general alkene reaction pattern in which the pi bond attacks an electrophile.",
    family: "Alkene addition",
    mechanismClass: "Carbocation",
    substrate: "Alkene",
    product: "Two new sigma bonds",
    reagents: ["Electrophile", "Nucleophile"],
    conditions: ["Depends on reagent pair"],
    steps: "Stepwise",
    intermediate: "Carbocation or bridged cation",
    selectivity: {
      regioselectivity: "Depends on intermediate stability",
      stereochemistry: "Depends on the reagent system",
      rearrangements: "Possible when a free carbocation forms",
    },
    keyIdea: "The electron-rich pi bond is the nucleophile that initiates the reaction.",
    competingReactionIds: [],
    relatedReactionIds: ["hydrohalogenation", "hydration", "halogenation"],
    prerequisiteNodeIds: ["lesson:chemical-bonding", "lesson:resonance"],
    mechanismHref: "/lab/electrophilic-addition",
    keywords: ["alkene", "pi bond", "electrophile", "addition"],
  },
  {
    id: "hydrohalogenation",
    title: "Hydrohalogenation",
    shortTitle: "HX addition",
    description: "Addition of HX across an alkene through protonation and halide attack.",
    family: "Alkene addition",
    mechanismClass: "Carbocation",
    substrate: "Alkene",
    product: "Alkyl halide",
    reagents: ["HCl, HBr, or HI"],
    conditions: ["No peroxide for the ionic pathway"],
    steps: "Stepwise",
    intermediate: "Carbocation",
    selectivity: {
      regioselectivity: "Markovnikov",
      stereochemistry: "Not stereospecific",
      rearrangements: "Possible",
    },
    keyIdea: "Protonation forms the most stable carbocation before halide capture.",
    competingReactionIds: ["radical-hbr"],
    relatedReactionIds: ["hydration", "oxymercuration-demercuration"],
    prerequisiteNodeIds: ["lesson:resonance"],
    mechanismHref: "/lab/hydrohalogenation",
    keywords: ["alkene", "markovnikov", "carbocation", "halide"],
  },
  {
    id: "hydration",
    title: "Acid-catalysed hydration",
    shortTitle: "Hydration",
    description: "Addition of water across an alkene through a carbocation intermediate.",
    family: "Alkene addition",
    mechanismClass: "Carbocation",
    substrate: "Alkene",
    product: "Alcohol",
    reagents: ["H₂O", "Dilute strong acid"],
    conditions: ["Aqueous acid"],
    steps: "Stepwise",
    intermediate: "Carbocation",
    selectivity: {
      regioselectivity: "Markovnikov",
      stereochemistry: "Not stereospecific",
      rearrangements: "Possible",
    },
    keyIdea: "Acid activates the alkene; water traps the most stable carbocation.",
    competingReactionIds: ["hydroboration-oxidation", "oxymercuration-demercuration"],
    relatedReactionIds: ["hydrohalogenation"],
    prerequisiteNodeIds: ["lesson:resonance"],
    mechanismHref: "/lab/hydration",
    keywords: ["alkene", "alcohol", "markovnikov", "acid"],
  },
  {
    id: "halogenation",
    title: "Alkene halogenation",
    shortTitle: "Halogenation",
    description: "Addition of Br₂ or Cl₂ through a bridged halonium-ion intermediate.",
    family: "Alkene addition",
    mechanismClass: "Halonium ion",
    substrate: "Alkene",
    product: "Vicinal dihalide",
    reagents: ["Br₂ or Cl₂"],
    conditions: ["Inert solvent"],
    steps: "Stepwise",
    intermediate: "Halonium ion",
    selectivity: {
      regioselectivity: "Not usually the main issue",
      stereochemistry: "Anti addition",
      rearrangements: "Not possible",
    },
    keyIdea: "A bridged halonium ion blocks same-face attack and prevents carbocation rearrangement.",
    competingReactionIds: [],
    relatedReactionIds: ["electrophilic-addition"],
    prerequisiteNodeIds: ["lesson:chemical-bonding"],
    mechanismHref: "/lab/halogenation",
    keywords: ["alkene", "halonium", "anti addition", "bromine"],
  },
  {
    id: "hydrogenation",
    title: "Catalytic hydrogenation",
    shortTitle: "Hydrogenation",
    description: "Reduction of an alkene on a metal surface using molecular hydrogen.",
    family: "Reduction",
    mechanismClass: "Surface catalysis",
    substrate: "Alkene",
    product: "Alkane",
    reagents: ["H₂", "Pd, Pt, or Ni catalyst"],
    conditions: ["Metal surface", "Hydrogen atmosphere"],
    steps: "Stepwise",
    intermediate: "Surface-bound species",
    selectivity: {
      regioselectivity: "Not applicable",
      stereochemistry: "Syn addition",
      rearrangements: "Not possible",
    },
    keyIdea: "Both hydrogens are delivered from the catalyst surface to the same face of the alkene.",
    competingReactionIds: [],
    relatedReactionIds: ["halogenation"],
    prerequisiteNodeIds: ["lesson:chemical-bonding"],
    mechanismHref: "/lab/hydrogenation",
    keywords: ["reduction", "alkene", "syn addition", "catalyst"],
  },
  {
    id: "hydroboration-oxidation",
    title: "Hydroboration–oxidation",
    shortTitle: "Hydroboration",
    description: "Two-step conversion of an alkene to an anti-Markovnikov alcohol.",
    family: "Alkene addition",
    mechanismClass: "Organoborane",
    substrate: "Alkene",
    product: "Alcohol",
    reagents: ["1. BH₃ or 9-BBN", "2. H₂O₂, OH⁻"],
    conditions: ["Anhydrous hydroboration then oxidative workup"],
    steps: "Stepwise",
    intermediate: "Organoborane",
    selectivity: {
      regioselectivity: "Anti-Markovnikov",
      stereochemistry: "Syn addition",
      rearrangements: "Not possible",
    },
    keyIdea: "Concerted hydroboration places boron at the less substituted carbon before oxidation replaces B with OH.",
    competingReactionIds: ["hydration", "oxymercuration-demercuration"],
    relatedReactionIds: ["radical-hbr"],
    prerequisiteNodeIds: ["lesson:chemical-bonding", "lesson:hybridization"],
    mechanismHref: "/lab/hydroboration-oxidation",
    keywords: ["alkene", "anti markovnikov", "syn addition", "alcohol"],
  },
  {
    id: "oxymercuration-demercuration",
    title: "Oxymercuration–demercuration",
    shortTitle: "Oxymercuration",
    description: "Markovnikov hydration through a bridged organomercury intermediate without rearrangement.",
    family: "Alkene addition",
    mechanismClass: "Organomercury",
    substrate: "Alkene",
    product: "Alcohol",
    reagents: ["1. Hg(OAc)₂, H₂O", "2. NaBH₄"],
    conditions: ["Aqueous solvent then reductive workup"],
    steps: "Stepwise",
    intermediate: "Mercurinium ion",
    selectivity: {
      regioselectivity: "Markovnikov",
      stereochemistry: "Often anti in the first stage; not strictly stereospecific overall",
      rearrangements: "Not possible",
    },
    keyIdea: "The bridged intermediate gives Markovnikov hydration while avoiding a free carbocation.",
    competingReactionIds: ["hydration", "hydroboration-oxidation"],
    relatedReactionIds: ["halogenation"],
    prerequisiteNodeIds: ["lesson:resonance"],
    mechanismHref: "/lab/oxymercuration-demercuration",
    keywords: ["alkene", "markovnikov", "alcohol", "no rearrangement"],
  },
  {
    id: "radical-hbr",
    title: "Radical HBr addition",
    shortTitle: "Radical HBr",
    description: "Peroxide-initiated chain addition of HBr that gives anti-Markovnikov regiochemistry.",
    family: "Alkene addition",
    mechanismClass: "Radical",
    substrate: "Alkene",
    product: "Alkyl bromide",
    reagents: ["HBr", "Peroxide initiator"],
    conditions: ["Heat or light"],
    steps: "Stepwise",
    intermediate: "Carbon radical",
    selectivity: {
      regioselectivity: "Anti-Markovnikov",
      stereochemistry: "Not stereospecific",
      rearrangements: "Classical carbocation rearrangements do not occur",
    },
    keyIdea: "The radical chain is selective because bromine adds to form the more stable carbon radical.",
    competingReactionIds: ["hydrohalogenation"],
    relatedReactionIds: ["hydroboration-oxidation"],
    prerequisiteNodeIds: ["lesson:chemical-bonding"],
    mechanismHref: "/lab/radical-hbr-addition",
    keywords: ["radical", "alkene", "anti markovnikov", "peroxide"],
  },
];

const reactionsById = new Map(reactions.map((reaction) => [reaction.id, reaction]));

export function getReaction(id: string): ReactionDefinition | undefined {
  return reactionsById.get(id);
}

export function getReactions(ids: readonly string[]): readonly ReactionDefinition[] {
  return ids.map((id) => reactionsById.get(id)).filter((reaction): reaction is ReactionDefinition => Boolean(reaction));
}
