export type {
  CarbonSignal,
  IrBand,
  MassSignal,
  ProtonSignal,
  SpectralAssignment,
  SpectroscopyCapabilities,
  SpectroscopyCompound,
  SpectroscopyDataset,
  SpectroscopyDatasetInput,
  SpectroscopySource,
  SpectrumAxis,
  SpectrumKind,
  SpectrumPoint,
} from "@/content/spectroscopy/spectroscopy-types";
